application:
  private:
    enabled: true
    ips:
      - 127.0.0.1
      - ${APPLICATION_PRIVATE_IP_1}
      - ${APPLICATION_PRIVATE_IP_2}
      - ${APPLICATION_PRIVATE_IP_3}
      - ${APPLICATION_PRIVATE_IP_4}
      - ${APPLICATION_PRIVATE_IP_5}
